/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A chat session with an AI agent.
 *
 * The session holds a fully configured agent that supports tool calls
 * (shell, glob, read_file) and interacts with an OpenAI-compatible LLM.
 *
 * The agent implements a simple loop: the model receives user input and
 * may output tool-call requests. The agent executes tools and sends the
 * results back to the model. By default each user turn is limited to 8
 * successful model rounds unless disabled. Optional Codex-style automatic
 * context compaction can summarize older history before sending the next
 * request. The loop continues until there are no more tool-call requests
 * or the iteration budget is exhausted.
 *
 * Built-in tools:
 * - **shell**: Runs arbitrary shell commands
 * - **glob**: Finds files using glob patterns
 * - **read_file**: Reads file content with line numbers
 */
export declare class AgentSession {
  /**
   * Creates a new agent session.
   *
   * @param config - Configuration for the agent (API key, model, etc.).
   * @param onIdle - Optional callback invoked when the agent becomes idle (finished processing).
   * @param onError - Optional callback invoked when an error occurs.
   * @param onTranscript - Optional callback invoked when a transcript event is generated.
   */
  constructor(config: AgentConfig, onIdle?: (((err: Error | null, ) => any)) | undefined | null, onError?: (((err: Error | null, arg: string) => any)) | undefined | null, onTranscript?: (((err: Error | null, arg: TranscriptEvent) => any)) | undefined | null)
  /**
   * Sends a message to the agent for processing.
   *
   * The agent will process the message, potentially make tool calls,
   * and generate transcript events via the onTranscript callback.
   * When processing is complete, the onIdle callback will be invoked.
   */
  sendMessage(message: string): void
}

/** Configuration for creating an agent session. */
export interface AgentConfig {
  /** OpenAI API key. */
  apiKey: string
  /** Model name (e.g. "gpt-4o"). Defaults to "gpt-4o" if not specified. */
  model?: string
  /** Base URL for the OpenAI-compatible API. Defaults to "https://api.openai.com/v1". */
  baseUrl?: string
  /** System prompt for the agent. */
  systemPrompt?: string
  /** Approximate token threshold that triggers automatic context compaction. */
  autoCompactTokenLimit?: number
  /** Override the default prompt used during context compaction. */
  compactPrompt?: string
  /** Maximum number of successful model rounds per user turn. Defaults to 8. */
  maxIterations?: number
  /** Disable the default per-turn iteration limit entirely. */
  disableIterationLimit?: boolean
}

/** Event emitted when the agent generates a transcript. */
export interface TranscriptEvent {
  /** The transcript text content. */
  text: string
  /** Source of the transcript: "user" or "assistant". */
  source: string
}
