pub mod proto;
pub mod sse;

use reqwest::{Client, Response, header};
use serde_json::Value;

use proto::*;
use sse::SseStream;

// ----------------------------
// Configuration
// ----------------------------

/// Builder for [`OpenAIConfig`].
pub struct OpenAIConfigBuilder {
  api_key: String,
  model: Option<String>,
  base_url: Option<String>,
}

impl OpenAIConfigBuilder {
  /// Creates a builder with the given API key.
  pub fn with_api_key(api_key: impl Into<String>) -> Self {
    Self {
      api_key: api_key.into(),
      model: None,
      base_url: None,
    }
  }

  /// Sets the model name.
  pub fn with_model(mut self, model: impl Into<String>) -> Self {
    self.model = Some(model.into());
    self
  }

  /// Sets a custom base URL.
  pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {
    self.base_url = Some(base_url.into());
    self
  }

  /// Builds the configuration.
  pub fn build(self) -> OpenAIConfig {
    OpenAIConfig {
      api_key: self.api_key,
      model: self.model.unwrap_or_else(|| "gpt-4o".to_string()),
      base_url: self
        .base_url
        .unwrap_or_else(|| "https://api.openai.com/v1".to_string()),
    }
  }
}

/// Configuration for the OpenAI-compatible provider.
#[derive(Clone)]
pub struct OpenAIConfig {
  pub api_key: String,
  pub model: String,
  pub base_url: String,
}

// ----------------------------
// Response types
// ----------------------------

/// A parsed tool call request from the model.
#[derive(Clone, Debug)]
pub struct ToolCallRequest {
  pub id: String,
  pub name: String,
  pub arguments: Value,
}

/// The reason the model finished generating.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FinishReason {
  Stop,
  ToolCalls,
}

/// A fully processed response from the model.
pub struct ModelResponse {
  /// The text content generated by the model.
  #[allow(dead_code)]
  pub transcript: String,
  /// The full assistant message for conversation history.
  pub raw_message: Message,
  /// Tool calls requested by the model.
  pub tool_calls: Vec<ToolCallRequest>,
  /// The reason the model stopped generating.
  pub finish_reason: FinishReason,
}

// ----------------------------
// Client
// ----------------------------

/// OpenAI-compatible API client.
///
/// Handles sending chat completion requests with streaming,
/// parsing SSE responses, and assembling tool call information.
pub struct OpenAIClient {
  client: Client,
  config: OpenAIConfig,
}

impl OpenAIClient {
  pub fn new(config: OpenAIConfig) -> Self {
    Self {
      client: Client::new(),
      config,
    }
  }

  /// Sends a chat completion request with streaming.
  ///
  /// The `on_transcript` callback is invoked for each text delta
  /// as the model generates its response.
  pub async fn send_request(
    &self,
    messages: &[Message],
    tools: &[ToolDef],
    on_transcript: impl Fn(String) + Send + 'static,
  ) -> Result<ModelResponse, String> {
    let request = ChatCompletionRequest {
      model: self.config.model.clone(),
      messages: messages.to_vec(),
      tools: tools.to_vec(),
      stream_options: Some(StreamOptions {
        include_usage: true,
      }),
      stream: true,
    };

    let resp = self
      .client
      .post(format!("{}/chat/completions", self.config.base_url))
      .header(
        header::AUTHORIZATION,
        format!("Bearer {}", self.config.api_key),
      )
      .header(header::CONTENT_TYPE, "application/json")
      .header(header::ACCEPT, "text/event-stream")
      .json(&request)
      .send()
      .await
      .and_then(Response::error_for_status)
      .map_err(|e| format!("{e}"))?;

    let mut sse = SseStream::new(resp);
    let mut transcript = String::new();
    let mut reasoning_content: Option<String> = None;
    let mut tool_calls: Vec<ToolCall> = Vec::new();
    let mut finish_reason = FinishReason::Stop;

    loop {
      let event = match sse.next_event().await {
        Ok(Some(event)) => event,
        Ok(None) => break,
        Err(err) => return Err(err),
      };

      let mut chunk: ChatCompletionChunk =
        serde_json::from_str(&event).map_err(|e| format!("Failed to parse chunk: {e}"))?;

      let Some(choice) = chunk.choices.pop() else {
        continue;
      };

      if let Some(reason) = choice.finish_reason {
        finish_reason = if reason == "tool_calls" {
          FinishReason::ToolCalls
        } else {
          FinishReason::Stop
        };
        break;
      }

      if let Some(content) = choice.delta.content {
        transcript.push_str(&content);
        on_transcript(content);
      }

      if let Some(rc) = &choice.delta.reasoning_content {
        reasoning_content.get_or_insert_default().push_str(rc);
      }

      if let Some(delta_tool_calls) = choice.delta.tool_calls {
        for tc in delta_tool_calls {
          if let Some(existing) = tool_calls.iter_mut().find(|t| t.index == tc.index) {
            // Merge partial tool call deltas
            if let Some(id) = tc.id {
              existing.id.get_or_insert_default().push_str(&id);
            }
            if let Some(ty) = tc.r#type {
              existing.r#type.get_or_insert_default().push_str(&ty);
            }
            if let Some(func) = tc.function {
              match &mut existing.function {
                Some(ref mut ef) => {
                  if let Some(name) = func.name {
                    ef.name.get_or_insert_default().push_str(&name);
                  }
                  if let Some(args) = func.arguments {
                    ef.arguments.get_or_insert_default().push_str(&args);
                  }
                }
                None => existing.function = Some(func),
              }
            }
          } else {
            tool_calls.push(tc);
          }
        }
      }
    }

    // Build the parsed tool call requests
    let parsed_tool_calls: Vec<ToolCallRequest> = tool_calls
      .iter()
      .map(|tc| {
        let id = tc.id.clone().unwrap_or_default();
        let name = tc
          .function
          .as_ref()
          .and_then(|f| f.name.clone())
          .unwrap_or_default();
        let arguments = tc
          .function
          .as_ref()
          .and_then(|f| f.arguments.as_deref())
          .and_then(|args| serde_json::from_str::<Value>(args).ok())
          .unwrap_or_default();
        ToolCallRequest {
          id,
          name,
          arguments,
        }
      })
      .collect();

    // Build the raw message for conversation history
    let raw_message = Message::Assistant {
      content: if transcript.is_empty() {
        None
      } else {
        Some(transcript.clone())
      },
      tool_calls: if tool_calls.is_empty() {
        None
      } else {
        Some(tool_calls)
      },
      reasoning_content,
    };

    Ok(ModelResponse {
      transcript,
      raw_message,
      tool_calls: parsed_tool_calls,
      finish_reason,
    })
  }
}
